  name: Create a docker image and push it to docker hub
  on:
    push:
      branches:
        - postgres-pgvector-semsearch

  jobs:
    build-deploy:
      name: build and deploy spring-api
      runs-on: ubuntu-latest
      services:
        postgres:
          image: ankane/pgvector:latest
          ports:
            - 5432:5432
          env:
            POSTGRES_DB: repository
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
          options: >-
            --health-cmd "pg_isready -U postgres -d repository"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=10
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/repository
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
      steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: setup jdk 21
          uses: actions/setup-java@v3
          with:
            java-version: '21' # Adjust the version to match your project
            distribution: 'temurin' # Use 'temurin' for OpenJDK

        - name: build the app
          run: |
            mvn clean
            mvn package -DskipTests=true
        - name: build the docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            dockerfile: Dockerfile
            push: false
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mosaico-repository:latest
        - name: login to docker hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: push the docker image to docker hub
          uses: docker/build-push-action@v4
          with:
            context: .
            dockerfile: Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mosaico-repository:latest